# Generated by Django 5.2 on 2025-06-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='commandes',
            field=models.ManyToManyField(blank=True, help_text='Commandes associées à ce panier', related_name='paniers', to='boutique.commande', verbose_name='Commandes'),
        ),
    ]
