# Generated by Django 5.2 on 2025-06-11 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite',
        ),
        migrations.AddField(
            model_name='produit',
            name='est_nouveau',
            field=models.BooleanField(default=True, verbose_name='Nouveau'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_principale',
            field=models.ImageField(blank=True, help_text='Image principale du produit', null=True, upload_to='produits/images/', verbose_name='Image Principale'),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_etoile',
            field=models.IntegerField(default=0, help_text='Note de 0 à 5', verbose_name='Étoiles'),
        ),
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default='', help_text='Identifiant unique pour le produit', max_length=128, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=1, help_text='Catégorie du produit', on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.categorie', verbose_name='Catégorie'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoyé', 'Envoyé'), ('livré', 'Livré')], default='en_attente', max_length=50)),
                ('mode_paiement', models.CharField(choices=[('carte', 'Carte'), ('paypal', 'PayPal'), ('mobile', 'Mobile')], default='mobile', max_length=50)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit', verbose_name='Produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/images/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boutique.produit')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'ordering': ['utilisateur', 'produit'],
            },
        ),
    ]
