# Generated by Django 5.2 on 2025-06-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_categorie_images_alter_produit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='images',
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/images/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boutique.produit')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
