# Generated by Django 5.2 on 2025-06-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_panier_commandes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panier',
            options={'ordering': ['utilisateur', 'date_commande'], 'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='quantite',
        ),
        migrations.AddField(
            model_name='panier',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, help_text='Date à laquelle le panier a été commandé', null=True, verbose_name='Date de commande'),
        ),
        migrations.AddField(
            model_name='panier',
            name='est_commande',
            field=models.BooleanField(default=False, help_text='Indique si le panier a été commandé', verbose_name='Commandé'),
        ),
    ]
