# Generated by Django 5.2 on 2025-06-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_remove_produit_images_imageproduit_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_principale',
            field=models.ImageField(blank=True, help_text='Image principale du produit', null=True, upload_to='produits/images/', verbose_name='Image Principale'),
        ),
    ]
